// The only place an order's status is allowed to change.
//
// Every caller — REST endpoints, Kafka consumers — goes through transition().
// That means the transition table in types.bal cannot be bypassed, and a
// replayed or out-of-order event cannot corrupt an order's state.

import ballerina/time;
import ballerina/uuid;

// Applies a status change to an order.
//
// Two cases are handled without error, on purpose:
//
//   - The order is already in the target state. This is a replayed event
//     or a duplicate HTTP call. Returning the order unchanged is what
//     makes consumers idempotent.
//
//   - The transition is illegal. This is a real error.
//
// + existing - the order to transition
// + target - the status to move to
// + origin - "HTTP" or the Kafka event name that caused this
// + actor - the customerId, restaurantId, or driverId responsible, if known
// + return - the updated order, or an error if the transition is illegal
public function transition(Order existing, OrderStatus target, string origin, string? actor) returns Order|error {
    if existing.status == target {
        return existing;
    }

    OrderStatus[] allowed = ALLOWED_TRANSITIONS[existing.status] ?: [];
    boolean legal = false;
    foreach OrderStatus s in allowed {
        if s == target {
            legal = true;
            break;
        }
    }
    if !legal {
        return error(string `illegal transition ${existing.status} -> ${target} for order ${existing.orderId}`);
    }

    string now = time:utcToString(time:utcNow());
    AuditEntry entry = {
        at: now,
        status: target,
        origin: origin,
        actor: actor
    };

    Order updated = existing;
    updated.status = target;
    updated.updatedAt = now;
    updated.history.push(entry);

    return updated;
}

// Builds a fresh order in CREATED state.
//
// + orderId - generated by the caller
// + req - the placement request
// + total - computed from req.items
// + return - a new Order in CREATED state
public function newOrder(string orderId, PlaceOrderRequest req, decimal total) returns Order {
    string now = time:utcToString(time:utcNow());
    OrderItem[] items = [];
    foreach PlaceOrderItem item in req.items {
        items.push({
            menuItemId: item.menuItemId,
            name: item.name,
            quantity: item.quantity,
            unitPrice: item.unitPrice
        });
    }

    AuditEntry first = {
        at: now,
        status: CREATED,
        origin: "HTTP",
        actor: ()
    };

    return {
        orderId: orderId,
        customerId: req.customerId,
        restaurantId: req.restaurantId,
        items: items,
        totalAmount: total,
        deliveryAddress: req.deliveryAddress,
        status: CREATED,
        reason: (),
        createdAt: now,
        updatedAt: now,
        history: [first]
    };
}

// Sums the line items. Kept here so the total is computed in exactly one
// place across the whole service.
//
// + items - the line items
// + return - the total
public function computeTotal(PlaceOrderItem[] items) returns decimal {
    decimal total = 0d;
    foreach PlaceOrderItem item in items {
        total += item.unitPrice * <decimal>item.quantity;
    }
    return total;
}

// Generates a fresh order identifier.
//
// + return - a new UUID v4
public function newOrderId() returns string => uuid:createType4AsString();
